yarnPath: .yarn/releases/yarn-4.9.3.cjs

nodeLinker: node-modules

npmRegistryServer: 'https://registry.npmjs.org'
npmAuthToken: '${NPM_PUBLISH_TOKEN:-}'
npmAlwaysAuth: false
npmPublishAccess: 'public'
